### PR TITLE
[Redesign] Add android gain effect disable

### LINKED ISSUE #1343: Unable to play any song on Lenovo tablet - Repeated
### Are you using the newest Version?

- [x] Yes, the issue happens on the newest version
- [x] No, there aren't any open issues about this. I checked!

### Type of Report

- [x] The app is unusable
- [ ] Something isn't quite right
- [ ] Some functionality isn't accessible to me
- [ ] Accessibility
- [ ] None of the above

### The exact version of the app

0.9.19

### Affected Devices/Platform

- [x] Android
- [ ] Android Auto
- [ ] iOS
- [ ] Linux
- [ ] MacOS (iOS version)
- [ ] MacOS (native)
- [ ] Windows

### Device

Lenovo Legion Y700 2025 (ZUI 17 / Android 15), Lenovo Xiaoxin Pad Pro 2022 (TB132FU, ZUI 16 / Android 14)

### Description & Steps to Reproduce

Try to play any song.

### Logs

[finamp-logs-0.9.19.zip](https://github.com/user-attachments/files/21845575/finamp-logs-0.9.19.zip)

### Additional Information

This is a repeated issue of #1238, since for me new updates never fixed this bug and there was no reaction to my comment.

### PR DESCRIPTION
**Pull request by Komodo5197**
Adds a setting to force android devices to use the basic volume control for replay gain instead of the loudness enhancer effect, and a fallback to enable automatically on error  This is a workaround for #1343.  This is currently untested due to the hardware dependency, but I felt like throwing a potential fix together because it seems someone new has hit this error on discord.

### CODE REVIEW

File: lib/main.dart [hunk 1]
```diff
@@ -368,6 +368,21 @@ Future<void> _setupOSIntegration() async {
       albumBuffer.asUint8List(albumImageBytes.offsetInBytes, albumImageBytes.lengthInBytes),
     );
   }
+
+  if (Platform.isAndroid) {
+    var themeModeChannel = MethodChannel("com.unicornsonlsd.finamp/set_native_theme");
+    GetIt.instance<ProviderContainer>().listen(finampSettingsProvider.themeMode, (_, mode) {
+      _mainLog.info("Setting android native theme to $mode");
+      themeModeChannel.invokeMethod("setNativeThemeMode", {
```
Comment (Chaphasilor) [inline lib/main.dart:376]: won't this lead to a color flash if the initial system theme doesn't match the app theme?

**Comment by Chaphasilor** [comment]
sorry about the merge conflict. I can resolve and merge later :)

File: lib/main.dart (hunk 1 above)
Comment (Komodo5197) [reply lib/main.dart:376]: No, this setting is actually persisted by the OS.  I think it might be able to flash during the first app load with the new code, I guess.  But after that the Os will remember and use the correct splash screen matching the in-app setting through the whole load.

Comment (Chaphasilor) [reply lib/main.dart:376]: Well, until the next time the theme is changed, I guess?  
Maybe you could invoke the platform method whenever the theme setting in Finamp is changed, too?

Comment (Komodo5197) [reply lib/main.dart:376]: The call being commented on is already inside a theme setting listener.

Comment (Chaphasilor) [reply lib/main.dart:376]: ah, my bad. let me just build this and see what happens ^^

Comment (Chaphasilor) [reply lib/main.dart:376]: okay, so I tried it out, coming from redesign with dark theme in the app but system in light mode, and on first launch the splash screen was light, and stayed that way. only once the music screen was shown did things turn dark. Next launch was with the dark splash screen.
Not what I expected given our discussion, but I think it's absolutely find with that behavior.

**Comment by Chaphasilor** [comment]
Thanks for these fixes!
