### PR TITLE
Various fixes

### LINKED ISSUE #1328: Local Network Address not saving
### Are you using the newest Version?

- [x] Yes, the issue happens on the newest version
- [x] No, there aren't any open issues about this. I checked!

### Type of Report

- [ ] The app is unusable
- [ ] Something isn't quite right
- [x] Some functionality isn't accessible to me
- [ ] Accessibility
- [ ] None of the above

### The exact version of the app

0.9.19

### Affected Devices/Platform

- [x] Android
- [ ] Android Auto
- [ ] iOS
- [x] Linux
- [ ] MacOS (iOS version)
- [ ] MacOS (native)
- [ ] Windows

### Device

_No response_

### Description & Steps to Reproduce

When clicking "Test both connections", I always get the error "FAILED to reach local address" even when using the same address in both the Public and Local address fields, and the public address is working fine.
This issue is happening on both Android and on the Linux Flatpak.

Linux:
Image

The same thing happens when using the actual local IP I want to use. I included the screenshot of the Public URL to show that it happens even when 100% confirmed that the address is accessible:

Image

Android log Screenshots (Logs attached below, but the screenshot shows the proper local Address, but incorrect port is being used)

Image

### Logs

<details>

  <summary>Logs Linux</summary>
  
=== METADATA ===
Device Info:
  Device Name: Freedesktop SDK
  Device Model: org.freedesktop.platform
  OS Version: 24.08 (Flatpak runtime)
  Platform: Linux
App Info:
  App Name: finamp
  Package Name: finamp
  Version: 0.9.19
  Build Number: 119
  Version History: 0.9.19 (119)
Server Info:
  Address Type: domainWithTld
  Port: 8096
  Protocol: http
  Version: Unknown
=== LOGS ===
  [WindowManager/FINER] 2025-08-11 11:20:28.327353: [WindowManager] onWindowEvent: blur
[PlayOnService/INFO] 2025-08-11 11:20:37.262705: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-11 11:20:37.282055: Received message: {"MessageId":"947213e4e3ca41fbbf85ed6c611a2199","MessageType":"KeepAlive"}
[WindowManager/FINER] 2025-08-11 11:20:41.431551: [WindowManager] onWindowEvent: focus
[Ayoo/SEVERE] 2025-08-11 11:20:49.512115: Invalid argument(s): No host specified in URI System/Endpoint
		#0      _HttpClient._openUrl (dart:_http/http_impl.dart:3019)
		#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2875)
		#2      IOClient.send (package:http/src/io_client.dart:117)
		#3      HttpCallInterceptor.intercept (package:chopper/src/interceptors/http_call_interceptor.dart:25)
		<asynchronous suspension>
		#4      InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46)
		<asynchronous suspension>
		#5      ResponseConverterInterceptor.intercept (package:chopper/src/interceptors/response_converter_interceptor.dart:43)
		<asynchronous suspension>
		#6      InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46)
		<asynchronous suspension>
		#7      InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46)
		<asynchronous suspension>
		#8      HttpAggregateLoggingChain.proceed (package:finamp/services/http_aggregate_logging_interceptor.dart:31)
		<asynchronous suspension>
		#9      HttpLoggingInterceptor.intercept (package:chopper/src/interceptors/http_logging_interceptor.dart:100)
		<asynchronous suspension>
		#10     HttpAggregateLoggingInterceptor.intercept (package:finamp/services/http_aggregate_logging_interceptor.dart:16)
		<asynchronous suspension>
		#11     InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46)
		<asynchronous suspension>
		#12     JellyfinSpecificInterceptor.intercept (package:finamp/services/jellyfin_api.dart:575)
		<asynchronous suspension>
		#13     InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46)
		<asynchronous suspension>
		#14     RequestConverterInterceptor.intercept (package:chopper/src/interceptors/request_converter_interceptor.dart:26)
		<asynchronous suspension>
		#15     InterceptorChain.proceed (package:chopper/src/chain/interceptor_chain.dart:46)
		<asynchronous suspension>
		#16     Call.execute (package:chopper/src/chain/call.dart:56)
		<asynchronous suspension>
		#17     ChopperClient.send (package:chopper/src/base.dart:175)
		<asynchronous suspension>
		#18     JellyfinApiHelper._pingSpecificServer (package:finamp/services/jellyfin_api_helper.dart:967)
		<asynchronous suspension>
		#19     JellyfinApiHelper.pingLocalServer (package:finamp/services/jellyfin_api_helper.dart:982)
		<asynchronous suspension>
		#20     Future.wait.<anonymous closure> (dart:async/future.dart:525)
		<asynchronous suspension>
		#21     _NetworkSettingsScreenState.build.<anonymous closure> (package:finamp/screens/network_settings_screen.dart:41)
		<asynchronous suspension>
		
[Chopper/INFO] 2025-08-11 11:20:50.349653: --> GET PUBLICURL/System/Endpoint
		Content-Type: application/json
		Authorization: MediaBrowser UserId="USER_ID", Token="TOKEN", Client="Finamp", Device="Freedesktop SDK",DeviceId="2280aca044c7593be4dd44f4640d4197-", Version="0.9.19"
		content-length: 0
		--> END GET
[Chopper/INFO] 2025-08-11 11:20:50.349887: <-- 200 OK GET PUBLICURL/System/Endpoint (837ms)
		date: Mon, 11 Aug 2025 18:20:49 GMT
		transfer-encoding: chunked
		content-encoding: gzip
		vary: Accept-Encoding
		x-response-time-ms: 8.8445
		content-type: application/json; charset=utf-8
		server: Kestrel
		content-length: 36
		
		{"IsLocal":false,"IsInNetwork":true}
		<-- END HTTP
[GlobalSnackbar/INFO] 2025-08-11 11:20:50.350477: Displaying message: FAILED to reach local address
[EnvironmentMetadata/WARNING] 2025-08-11 11:20:59.922917: Failed to load server info: TimeoutException: Failed to fetch server info within the timeout period.
  
</details> 

<details>

  <summary>Logs Android</summary>

=== METADATA ===
Device Info:
  Device Name: google
  Device Model: Pixel 7
  OS Version: 16
  Platform: Android
App Info:
  App Name: Finamp
  Package Name: com.unicornsonlsd.finamp
  Version: 0.9.19
  Build Number: 119
  Version History: 0.9.19 (119)
Server Info:
  Address Type: domainWithTld
  Port: 8096
  Protocol: http
  Version: Unknown
=== LOGS ===
[PlayOnService/INFO] 2025-08-10 11:26:08.646793: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-10 11:26:08.653115: Received message: {"MessageId":"d754be970b7e4120882ec11e6c862132","MessageType":"KeepAlive"}
[Ayoo/SEVERE] 2025-08-10 11:26:24.316196: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = HOST, port = PORT, uri=HOMEURL(INACTIVE)/System/Endpoint
[Chopper/INFO] 2025-08-10 11:26:24.337193: --> GET PUBLICURL/System/Endpoint
		Content-Type: application/json
		Authorization: MediaBrowser UserId="USER_ID", Token="TOKEN", Client="Finamp", Device="Pixel 7",DeviceId="dd3c70fc-5aea-4635-0f26-4273bbb74104-", Version="0.9.19"
		content-length: 0
		--> END GET
[Chopper/INFO] 2025-08-10 11:26:24.337606: <-- 200 OK GET PUBLICURL/System/Endpoint (35ms)
		date: Sun, 10 Aug 2025 18:26:23 GMT
		transfer-encoding: chunked
		content-encoding: gzip
		vary: Accept-Encoding
		x-response-time-ms: 13.0776
		content-type: application/json; charset=utf-8
		server: Kestrel
		content-length: 36
		
		{"IsLocal":false,"IsInNetwork":true}
		<-- END HTTP
[GlobalSnackbar/INFO] 2025-08-10 11:26:24.338387: Displaying message: FAILED to reach local address
[Ayoo/SEVERE] 2025-08-10 11:26:30.660327: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = HOST, port = PORT, uri=HOMEURL(INACTIVE)/System/Endpoint
[Chopper/INFO] 2025-08-10 11:26:30.666190: --> GET PUBLICURL/System/Endpoint
		Content-Type: application/json
		Authorization: MediaBrowser UserId="USER_ID", Token="TOKEN", Client="Finamp", Device="Pixel 7",DeviceId="dd3c70fc-5aea-4635-0f26-4273bbb74104-", Version="0.9.19"
		content-length: 0
		--> END GET
[Chopper/INFO] 2025-08-10 11:26:30.666316: <-- 200 OK GET PUBLICURL/System/Endpoint (14ms)
		date: Sun, 10 Aug 2025 18:26:30 GMT
		transfer-encoding: chunked
		content-encoding: gzip
		vary: Accept-Encoding
		x-response-time-ms: 0.4377
		content-type: application/json; charset=utf-8
		server: Kestrel
		content-length: 36
		
		{"IsLocal":false,"IsInNetwork":true}
		<-- END HTTP
[GlobalSnackbar/INFO] 2025-08-10 11:26:30.666635: Displaying message: FAILED to reach local address
[PlayOnService/INFO] 2025-08-10 11:26:38.648582: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-10 11:26:38.664037: Received message: {"MessageId":"55ae09614bec4930a8a631b5b1db6690","MessageType":"KeepAlive"}
[PlayOnService/INFO] 2025-08-10 11:27:08.647944: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-10 11:27:08.664582: Received message: {"MessageId":"d2bf50d5a2be482193c1a8a0af433cad","MessageType":"KeepAlive"}
[PlayOnService/INFO] 2025-08-10 11:27:38.647281: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-10 11:27:38.659322: Received message: {"MessageId":"9eeba7ec226443de9a9bfb6d3e3ffa01","MessageType":"KeepAlive"}
[PlayOnService/INFO] 2025-08-10 11:28:08.647536: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-10 11:28:08.665550: Received message: {"MessageId":"a15a90aee90043d5bbdd8955873ccc8f","MessageType":"KeepAlive"}
[PlayOnService/INFO] 2025-08-10 11:28:38.648565: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-10 11:28:38.664596: Received message: {"MessageId":"6718f8a9f7ff4542ab0c9ffb4a409322","MessageType":"KeepAlive"}
[Ayoo/SEVERE] 2025-08-10 11:28:53.333135: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = HOST, port = PORT, uri=HOMEURL(INACTIVE)/System/Endpoint
[Chopper/INFO] 2025-08-10 11:28:53.466163: --> GET PUBLICURL/System/Endpoint
		Content-Type: application/json
		Authorization: MediaBrowser UserId="USER_ID", Token="TOKEN", Client="Finamp", Device="Pixel 7",DeviceId="dd3c70fc-5aea-4635-0f26-4273bbb74104-", Version="0.9.19"
		content-length: 0
		--> END GET
[Chopper/INFO] 2025-08-10 11:28:53.466703: <-- 200 OK GET PUBLICURL/System/Endpoint (144ms)
		date: Sun, 10 Aug 2025 18:28:52 GMT
		transfer-encoding: chunked
		content-encoding: gzip
		vary: Accept-Encoding
		x-response-time-ms: 0.6015
		content-type: application/json; charset=utf-8
		server: Kestrel
		content-length: 36
		
		{"IsLocal":false,"IsInNetwork":true}
		<-- END HTTP
[GlobalSnackbar/INFO] 2025-08-10 11:28:53.467729: Displaying message: FAILED to reach local address
[PlayOnService/INFO] 2025-08-10 11:29:08.648539: Sent KeepAlive message through websocket
[PlayOnService/FINEST] 2025-08-10 11:29:08.662185: Received message: {"MessageId":"7eb911de84394b9f9f99ca23ce5bdcca","MessageType":"KeepAlive"}
[EnvironmentMetadata/WARNING] 2025-08-10 11:29:22.874591: Failed to load server info: TimeoutException: Failed to fetch server info within the timeout period.
[Chopper/INFO] 2025-08-10 11:29:22.898330: --> GET PUBLICURL/System/Info/Public
		Content-Type: application/json
		Authorization: MediaBrowser UserId="USER_ID", Token="TOKEN", Client="Finamp", Device="Pixel 7",DeviceId="dd3c70fc-5aea-4635-0f26-4273bbb74104-", Version="0.9.19"
		content-length: 0
		--> END GET
[Chopper/INFO] 2025-08-10 11:29:22.898514: <-- 200 OK GET PUBLICURL/System/Info/Public (26ms)
		date: Sun, 10 Aug 2025 18:29:22 GMT
		transfer-encoding: chunked
		content-encoding: gzip
		vary: Accept-Encoding
		x-response-time-ms: 0.6229
		content-type: application/json; charset=utf-8
		server: Kestrel
		content-length: 221
		
		{"LocalAddress":"HOMEURL(INACTIVE):8096","ServerName":"william-media-pc","Version":"10.10.7","ProductName":"Jellyfin Server","OperatingSystem":"","Id":"84666e6f17ab4c849ed895002b1c28b8","StartupWizardCompleted":true}
		<-- END HTTP

</details

### Additional Information

On Linux, the Local Network Address never saves and is always blank when I go back to the page. In fact from the logs it appears blank to the Test feature even though it shows in the UI,

On Android, the Local address has been saved, but the port (8096) was stripped off. And no matter how many times I add it back and click test, the screen always removes it. Even if I delete the Local address value and leave the page, coming back shows the Address was not removed. 

In both cases is seems like the Network screen ignores whatever I put in that box and uses whatever it has saved somewhere else when Testing.

### LINKED ISSUE #1391: Downloads: Folder Format
### Are you using the newest Version?

- [x] Yes, the issue happens on the newest version
- [x] No, there aren't any open issues about this. I checked!

### Type of Report

- [ ] The app is unusable
- [x] Something isn't quite right
- [ ] Some functionality isn't accessible to me
- [ ] Accessibility
- [ ] None of the above

### The exact version of the app

0.9.19

### Affected Devices/Platform

- [x] Android
- [ ] Android Auto
- [ ] iOS
- [ ] Linux
- [ ] MacOS (iOS version)
- [ ] MacOS (native)
- [ ] Windows

### Device

_No response_

### Description & Steps to Reproduce

Downloads get sorted into weird folders:

- The selected folder will always contain an additional Finamp-Folder. 
- The path does not contain the album, only the artist, leading to unsorted files
- Downloads generate empty, unrelated folders of different artists

All of this makes accessing and navigating the download-directory peoblematic.

It would be great if the folderpath would contain the album, and no additional prefix.

### Logs

<details>

  <summary>Logs</summary>
  
  PLACE YOUR *FULL* LOGS HERE, or attach them as a file
  you may censor any private information (although Finamp tries to remove that automatically), just please don't edit out larger sections.
  
</details> 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Chaphasilor**
## Changes

- Lyrics are now always fetched during a download repair, for each track. This is the only way to ensure a full repair/sync actually updates the lyrics
  - fixes multiple reports on Discord
- Updated downloads file structure for human-readable (i.e., external) downloads
  - fixes #1391 (although we still create a "Finamp" directory, I wasn't sure if this is strictly necessary)
  
I might keep adding things here, where I'd like another pair of eyes to take a look.

### CODE REVIEW

File: lib/services/downloads_service_backend.dart [hunk 1]
```diff
@@ -1552,12 +1555,45 @@ class DownloadsSyncService {
...
 
+  /// Builds the subdirectory ($1) and base filename ($2) for track and image files
+  /// Used by [_downloadTrack] and [_downloadImage] for a consistent directory structure.
+  (String, String) _getDownloadPath(DownloadItem downloadItem) {
+    var downloadLocation = downloadItem.syncDownloadLocation!;
+    var item = downloadItem.baseItem!;
+    String fileName;
+    String subDirectory;
+    if (downloadLocation.useHumanReadableNames) {
+      fileName = _filesystemSafe(
```
Comment (Komodo5197) [inline lib/services/downloads_service_backend.dart:1569]: I'm not sure I like the idea of assigning the item name to images.  Assigning a specific track's name to an image that could be associated with, as an example, every track in the album and the album itself could be a bit misleading, and if the album itself gets selected I think the image would end up outside the album folder?  And we're still going to end up with a bunch of images for things like artists and genres cluttering up the root directory.  It might make sense to just give up on human readable image locations and stick all the images into a dedicated images folder?

File: lib/services/downloads_service_backend.dart [hunk 2]
```diff
@@ -1552,12 +1555,45 @@ class DownloadsSyncService {
...
+        "${item.indexNumber != null ? "[${item.indexNumber}] " : ""}${item.artists?.isNotEmpty ?? false ? "${item.artists?.joinNonNull(", ")} - " : ""}${item.name}",
```
Comment (Komodo5197) [inline lib/services/downloads_service_backend.dart]: Is it really worth putting all the artists into the filenames?  This could potentially make them very long.

**Comment by Chaphasilor** [comment]
FYI while playing around with this I noticed that when a downloaded album is loaded on the albums tab, and then gets deleted, it will have a blank cover until the tab is reloaded. Might be related to your changes to image caching, if I remember correctly?

File: lib/services/downloads_service_backend.dart (hunk 1 above)
Comment (Chaphasilor) [reply lib/services/downloads_service_backend.dart:1569]: So my reasoning was to preserve as much metadata in the filenames as possible. The naming should never be incorrect, we just avoid duplicates if all other tracks have the same cover. So I don't really see the issue with doing things this way.  
I also noticed the issue with album covers ending up outside the album directory, but - although annoying - this doesn't seem too problematic.  
One thing I was debating is just throwing all images into an `images` subdirectory, that could also work to keep things tidy.  
Finally, Jellyfin does expose the original file path on the server, so we could use that to exactly re-create the server-side file structure (sanitized of course). That might be an elegant solution that actually would be usable as a (partial) library backup.

File: lib/services/downloads_service_backend.dart (hunk 2 above)
Comment (Chaphasilor) [reply lib/services/downloads_service_backend.dart]: You're right, that could be an issue. I was trying to have a consistent format, and since Jellyfin doesn't expose a "main" artist I wanted to include all. I'll switch this to use the original file name (if available), or fall back to just the first artist.

File: lib/components/global_snackbar.dart [hunk 3]
```diff
@@ -117,5 +159,14 @@ class GlobalSnackbar {
         duration: const Duration(seconds: 4),
       ),
     );
+
+    // When this snackbar fully closes (timeout or swipe), clear the key if it matches, allowing future identical errors.
+    if (isNetworkError && dedupKey != null) {
```
Comment (Komodo5197) [inline lib/components/global_snackbar.dart]: We don't need the isNetweorkError check here.

File: lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart [hunk 4]
```diff
@@ -10,16 +10,55 @@ import 'package:get_it/get_it.dart';
 class LocalNetworkAddressSelector extends ConsumerStatefulWidget {
   const LocalNetworkAddressSelector({super.key});
 
+  // Externally callable hook to force committing pending edits before actions (e.g., test connection)
+  static Future<void> Function()? commitPendingEdits;
```
Comment (Komodo5197) [inline lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart]: I'd prefer this not be global, even if we only expect one widget at once.  I think the way to do this is to give the widget a key on creation, and then call key.currentState.commitIfChanged.

File: lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart [hunk 5]
```diff
@@ -29,6 +68,9 @@ class _LocalNetworkAddressSelector extends ConsumerState<LocalNetworkAddressSele
     bool featureEnabled = user?.preferLocalNetwork ?? DefaultSettings.preferLocalNetwork;
 
     _controller ??= TextEditingController(text: address);
```
Comment (Komodo5197) [inline lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart]: We shoulkd set up _controller and _lastcommittedValue inside of initState.

File: lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart [hunk 6]
```diff
@@ -39,15 +81,18 @@ class _LocalNetworkAddressSelector extends ConsumerState<LocalNetworkAddressSele
...
+          focusNode: _focusNode,
           textAlign: TextAlign.center,
           keyboardType: TextInputType.url,
-          onSubmitted: (value) async {
-            if (!value.startsWith("http")) {
-              return GlobalSnackbar.message((context) => AppLocalizations.of(context)!.missingSchemaError);
-            }
-            GetIt.instance<FinampUserHelper>().currentUser?.update(newLocalAddress: value);
-            await changeTargetUrl();
+          onTapOutside: (_) {
```
Comment (Komodo5197) [inline lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart]: Is all of this needed with the focus listener?  I don't know much about the focus system, but it feels like at least some of this should be redundant.

File: lib/services/downloads_service_backend.dart (hunk 1 above)
Comment (Komodo5197) [reply lib/services/downloads_service_backend.dart:1569]: If we reliably get the full server path, just using that wouldn't be crazy.  Although that introduces the possibility of issues relating to parsing path separators and usable characters across different filesystems.  I do like using the original filename, at the very least.  Although maybe we should add a random id at the end to handle possible collisions due to possibly grouping items which were in separate folders.  I think the previous method also could theoretically generate collisions.  

I think I'd prefer just shoving everything into an images folder.  The reason I don't like the track names is that it implies precision we don't have.  You see an image for track 13 and wonder where all the other track images are.  I don't think having the images in the audio folder structure is actually useful anyway.

Comment (Chaphasilor) [reply lib/services/downloads_service_backend.dart:1569]: then I'll move images into their own subdirectory and go back to using UUIDs, and also append a random ID to each original file name 👍

File: lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart (hunk 6 above)
Comment (Chaphasilor) [reply lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart]: I honestly haven't tested this extensively, I just wanted to make sure it actually saves the value

File: lib/screens/network_settings_screen.dart [hunk 7]
```diff
@@ -33,14 +33,16 @@ class _NetworkSettingsScreenState extends State<NetworkSettingsScreen> {
...
+          PublicAddressSelector(),  
           LocalNetworkSelector(),
-          LocalNetworkAddressSelector(),
+          LocalNetworkAddressSelector(key: LocalNetworkAddressSelector.localNetworkAddressKey),
           TextButton(
             onPressed: () async {
               // Ensure any pending edits in the local network address field are committed first
-              if (LocalNetworkAddressSelector.commitPendingEdits != null) {
-                await LocalNetworkAddressSelector.commitPendingEdits!();
+              final widgetState = LocalNetworkAddressSelector.localNetworkAddressKey.currentState;
```
Comment (Komodo5197) [inline lib/screens/network_settings_screen.dart]: This key doesn't need to be a static global, just create it as a local variable.  I think if you make the _LocalNetworkAddressSelector class public you can set that as the key type and you shouldn't need to cast anything, but I'm not 100% sure of that.

File: lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart [hunk 8]
```diff
@@ -10,28 +10,34 @@ import 'package:get_it/get_it.dart';
...
 class _LocalNetworkAddressSelector extends ConsumerState<LocalNetworkAddressSelector> {
+
   TextEditingController? _controller;
   FocusNode? _focusNode;
   String _lastCommittedValue = '';
 
   @override
   void initState() {
     super.initState();
+    FinampUser? user = ref.read(FinampUserHelper.finampCurrentUserProvider).valueOrNull;
```
Comment (Komodo5197) [inline lib/components/NetworkSettingsScreen/prefer_local_network_address_selector.dart]: As mentioned in the other PR, I don't really like using ref.read, and would prefer to just directly access the setting.

File: lib/screens/network_settings_screen.dart (hunk 7 above)
Comment (Chaphasilor) [reply lib/screens/network_settings_screen.dart]: thanks for the tip, that worked.

**Comment by Komodo5197** [comment]
Regarding the album cover being blank after deleting, this is presumably related to the image caching or providers, but I'm not really sure how it would have happened.  If we re-evaluated the albumImageProvider we should have gotten a correct reference to the network image, and if we didn't we would still have the exact same file image provider, which you would expect to hit the decoded image in the flutter image cache.  I made a basic try to reproduce this but failed.  Had the relevant image been involved in the queue at any point, because the logic there is a bit more complex and has more room for errors.

**Comment by Chaphasilor** [comment]
Hmm, I just tried reproducing it just now and it's not happening anymore, no matter how I download, queue, hot restart, refresh, or let images fail to download. It was very consistent for me at some point though, but whatever. If I encounter it again I'll try to record better reproduction steps.

**Comment by Chaphasilor** [comment]
Okay, this should be done now. Images are now stored in an `images` subdirectory using a plain UUID, and original track names are combined with metadata-based directory trees and the first 8 characters of the item ID to get a robust structure.  
I've opted not to use the path as I'm not sure how long it will be around. I've heard that the path was only kept because the Kodi addon used it for direct playback of media files, which is no longer supported, so I'm not too confident basing logic on this (even if there's a fallback).

Feel free to merge if this looks good to you!

**Comment by Komodo5197** [comment]
The comments and code still suggest that _getDownloadPath is used for both tracks and images, but it looks like you broke them up again and images are handled internally, so you should clean that up.  Other than that, it looks good to me.

**Comment by Chaphasilor** [comment]
Ah, seems like I missed a part of the comment when removing the references to images. Should be clearer now.
